/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        // map<char, int> a;

        // for (const char& i: s) ++a[i];

        // map<char, int> b;
        
        // for (const char& i: t) {
        //     if (a.find(i) != a.end()) {
        //         ++b[i];
        //         if (b[i] > a[i]) return i;
        //     } else return i;
        // }

        // return 'a';

        sort(s.begin(), s.end());
        sort(t.begin(), t.end());

        for (int i = 0; i < s.size(); ++i) {
            if (s[i] != t[i]) return t[i];
        }

        return t[s.size()];
    }
};
